blank_issues_enabled: true
contact_links:
  - name: ğŸ“ Official Documentation
    url: https://docs.btcpayserver.org
    about: Check our documentation for answers to common questions
  - name: ğŸ’¬ Community Support Chat
    url: https://chat.btcpayserver.org/
    about: Ask general questions and get community support in real-time
  - name: ğŸ™ PrestaShop Support
    url: https://www.prestashop-project.org/support/
    about: Read up on how you can get support for your PrestaShop store
